### ISSUE TITLE
Make an exception for Pale Moon 25  

### ISSUE THREAD

**Issue by LimboSlam** [nmaier/about-addons-memory#17]
Can you please make an exception for PM or at least downgrade your compatibility support for FF 33+ to FF 31+, so I can have the latest. Here's PM UA, "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.2) Gecko/20150122 Firefox/31.9 PaleMoon/25.2.1." This would be greatly appreciated! Thanks.  :)

**Comment by nmaier** [comment]
I'm not gonna spend any time on compatibility code for pale moon/old Firefox. If anybody wants to contribute some, I'm open for that as long as the changes are reasonable.
