### ISSUE TITLE
No `about:addons-memory` in FF 41.0.1

### ISSUE THREAD

**Issue by alexeyr** [nmaier/about-addons-memory#22]
Just installed the current version from https://addons.mozilla.org/en-us/firefox/addon/about-addons-memory/, `about:addons-memory` shows "The address isn't valid" and it isn't listed in `about:about`.

**Comment by yfdyh000** [comment]
Works for me in 41.0.1. Broken in Nightly 44, #21.

**Comment by alexeyr** [comment]
After disabling a few addons, it works. Probably a duplicate of #1.
